# Generated by Django 5.1.7 on 2025-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='module',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
