# Generated by Django 5.1.7 on 2025-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_assistentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('assistente', models.CharField(max_length=200)),
                ('revendedor_cliente', models.CharField(max_length=200)),
                ('certame_negocio', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
                ('processador', models.CharField(max_length=200)),
                ('quantidade', models.CharField(max_length=200)),
                ('valor_unitario', models.CharField(max_length=200)),
                ('valor_total', models.CharField(max_length=200)),
                ('verba_concedida', models.CharField(max_length=200)),
                ('verba_concedida_porcentagem', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('aprovador', models.CharField(max_length=200)),
                ('data_hora_aprovacao_recusa', models.CharField(max_length=200)),
            ],
        ),
    ]
