# Generated by Django 5.1.7 on 2025-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='data_faturamento',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposals',
            name='nf',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
