# Generated by Django 5.2.4 on 2025-08-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposals_data_faturamento_proposals_nf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='produto',
            new_name='modelo',
        ),
    ]
