# Generated by Django 5.2.4 on 2025-08-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_modelos_processadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='nf',
            new_name='nf_preco_direto',
        ),
    ]
