# Generated by Django 5.2.4 on 2025-08-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_rename_nf_proposals_nf_preco_direto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='aprovador',
            new_name='aprovador_reprovador',
        ),
        migrations.RenameField(
            model_name='proposals',
            old_name='data_faturamento',
            new_name='data_abatimento',
        ),
        migrations.RenameField(
            model_name='proposals',
            old_name='nf_preco_direto',
            new_name='forma_abatimento',
        ),
    ]
